Supply plurals forms header to Gettext.Plural callbacks
elixir-gettext/gettext pull request #343
Opened 2023-01-15 15:18 UTC by maennchen

Closes #318

This makes it possible to react precisely to the header instead of using predefined formats.

This comit also introduces `Gettext.Plural.compile_plural/3` to shift work into compile time to possibly improve the performance.

2023-01-15 15:20 UTC, maennchen commented on lib/gettext/merger.ex
> +  defp read_plural_forms_from_headers(messages) do
Why do we have this code? The current default implementation can't handle the header completely and would create an inconsistency.

I think we should probably completely remove this function and delegate all work to `nplurals/2`.

2023-01-15 15:22 UTC, maennchen commented on lib/gettext/plural.ex
> +  @type pluralization_context :: %{optional(:plural_forms_header) => String.t()}
I've defined the new parameter in a map. That way we can decide to add further context in the future without a breaking change.

2023-01-15 17:09 UTC, whatyouhide commented
> shift work into compile time to possibly improve the performance

If we don't know if this improves performance, I don't think we should do it for now. Let's solve it if it ever becomes a problem?

2023-01-15 17:09 UTC, whatyouhide commented
@maennchen also, can you elaborate on the purpose of this PR in more details? I'm not really following 😄

2023-01-15 19:26 UTC, maennchen commented
@whatyouhide

> If we don't know if this improves performance, I don't think we should do it for now. Let's solve it if it ever becomes a problem?

That highly depends on the implementation of that behaviour. I know that I can make it faster in ExpoPluralForms.

That description should probably be worded differently.

> @maennchen also, can you elaborate on the purpose of this PR in more details? I'm not really following smile

Sure :)

The purpose of this PR is that the plural form header is passed into `Gettext.Plural` implementations.

Therefore implementations can make decisions based on that header.

This will allow it to implement an ExpoPluralForms implementation of the behaviour.

## Current behaviour

Gettext has a list of known locales for which `plural` is implemented. Since that list identifies rule by the locale name, the index is looked up by `locale` & `count`.

## ExpoPluralForms behaviour

For various languages, there's not a single way to represent plural rules.

For example for chinese there's two different rules depending on the context. (`nplurals=1; plural=0;` & `nplurals=2; plural=(n > 1);`)

Also in my own language (swiss german) there's some debate of how to handle `0` counts and depending on the dialect, either new singular case (0) or many (1) applies.

Those rules & differences can be represented using the plural forms header.

By supplying the plural forms header to the callbacks, the implementation can make decisions as they were intended in gettext.

2023-01-15 20:08 UTC, maennchen commented
@whatyouhide Performance comparison (extended from https://github.com/elixir-gettext/expo_plural_forms/pull/33#issuecomment-1383212655) to illustrate what would happen if the header was parsed on every index call:

```elixir
Mix.install([{:benchee, "~> 1.1"}, {:expo_plural_forms, path: "."}])

{:ok, arabic} = ExpoPluralForms.Known.plural_form("ar")

defmodule Arabic do
  def index(n), do: unquote(ExpoPluralForms.compile_index(arabic))
end

Benchee.run(
  %{
    "precompiled" => fn ->
      Arabic.index(17)
    end,
    "without" => fn ->
      ExpoPluralForms.index(arabic, 17)
    end,
    "including parse" => fn ->
      {:ok, arabic} = ExpoPluralForms.parse(" nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5);")
      ExpoPluralForms.index(arabic, 17)
    end
  },
  time: 10,
  memory_time: 2
)
```

Result:

```
Operating System: Linux
CPU Information: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
Number of Available Cores: 8
Available memory: 46.77 GB
Elixir 1.14.2
Erlang 25.2

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 10 s
memory time: 2 s
reduction time: 0 ns
parallel: 1
inputs: none specified
Estimated total run time: 42 s

Benchmarking including parse ...
Benchmarking precompiled ...
Benchmarking without ...

Name                      ips        average  deviation         median         99th %
precompiled           12.75 M       78.44 ns ±11373.62%          72 ns         100 ns
without                4.89 M      204.65 ns ±17541.84%         173 ns         348 ns
including parse        0.35 M     2833.62 ns   ±846.85%        2546 ns        4091 ns

Comparison: 
precompiled           12.75 M
without                4.89 M - 2.61x slower +126.21 ns
including parse        0.35 M - 36.12x slower +2755.17 ns

Memory usage statistics:

Name               Memory usage
precompiled                 0 B
without                     0 B - 1.00x memory usage +0 B
including parse          9928 B - ∞ x memory usage +9928 B

**All measurements for memory usage were the same**
```

2023-01-15 20:36 UTC, josevalim commented
> By supplying the plural forms header to the callbacks, the implementation can make decisions as they were intended in gettext.

I think this is approaching the problem based on the current solution but, given the limitations you added, I would say the problem needs to be reworked altogether. Likely we want to compile the rules encoded in the header as part of the backend compilation?

When you say the PluralForms header, is that a header for the .po file or specific to a given translation/msgid?

2023-01-15 20:40 UTC, maennchen commented
@josevalim The plural forms header is in the `.po` header and not per message.

The idea with `compile_plural` was to compile the rule once per backend and call it from there.

Based on the discussion over in ExpoPluralForms (performance), I think it would make more sense to go a plug like approach. There could be some kind of `init` callback to do preparation works like header parsing and then a normal function call with the init result to calculate the index.

I'll put the PR back into draft state and implement a cleaner solution.

2023-01-15 20:44 UTC, josevalim commented
> For example for chinese there's two different rules depending on the context. (nplurals=1; plural=0; & nplurals=2; plural=(n > 1);)

and how do you determine which one to use? :)

2023-01-15 21:14 UTC, maennchen commented
@josevalim  The user of the library can decide which rule to use when he sets the header in the `.po` file.

Many tools like [Poedit](https://poedit.net/) help a user setting up the headers as well.

We have an example of that here in the source: https://github.com/elixir-gettext/gettext/blob/2ebe8066d6309ea2d810beb93e38433fef6f5071/test/fixtures/po_editors/poedit.po#L13

2023-01-15 21:29 UTC, whatyouhide commented
Yeah, I think the `Plural-Form` header in each PO file is pretty neat. I think compiling the `Plural-Forms` header **once** is a no-brainer, because we can parse it into an Elixir data structure really easily. I think "precompiled" vs "without" in your benchmarks show that "without" is probably a good compromise between simplicity and speed.

2023-01-15 21:41 UTC, maennchen commented
@josevalim / @whatyouhide I pushed a new version that is a lot simpler and does not cause any changes in the behaviour. Only a new callback is added.

2023-01-15 22:19 UTC, maennchen commented
Example implementation: https://github.com/elixir-gettext/expo_plural_forms/pull/36

2023-01-16 10:48 UTC, maennchen commented on lib/gettext/plural.ex
> +    case read_plural_forms_from_headers(plural_forms_header) do
This is here to keep `gettext.merge --plural-forms 7` working.

It is however not consistent internally. I could for example merge with `--plural-forms 1` in a language that has 2+ plural forms.

The using `ngettext`, the correct plural forms would not be defined and therefore always result in a missing translation.

---

As an laternate solution, we could remove the option entirely and make the `Gettext.Plural` implementation only work on known formats. If a user wants to add / change a language, he would need to add his own implementation as decribed here: https://github.com/elixir-gettext/gettext/blob/41e16f2f9a84e0b9d8ac77122a623d4d8e7e9a3a/lib/gettext/plural.ex#L41

Even though I personally like option 2 a lot more, I decided to go with the solution that does not cause breaking changes.

2023-01-19 12:58 UTC, whatyouhide requested changes
Left a bunch of comments!

2023-01-19 12:58 UTC, whatyouhide commented on lib/gettext/plural.ex
> +  @callback plural(opts(), count :: integer()) :: non_neg_integer()
Nit: let's leave the name, it's helpful in documentation.

```suggestion
  @callback plural(opts(), count :: integer()) :: plural_form :: non_neg_integer()
```

2023-01-19 12:58 UTC, whatyouhide commented on lib/gettext/plural.ex
> +  Fallback if not implemented: `"nplurals={nplurals};"`
```suggestion
  Fallback if not implemented: `"nplurals={nplurals};"`.
```

2023-01-19 12:58 UTC, whatyouhide commented on lib/gettext/plural.ex
> +  @callback plural_forms_header(locale()) :: String.t() | nil
When does this return `nil`, and what does that mean semantically?

2023-01-19 12:58 UTC, whatyouhide commented on lib/gettext/plural.ex
> +  Returns the plural forms header value for a given locale
```suggestion
  Returns the plural forms header value for the given `locale`.

```

2023-01-19 12:58 UTC, whatyouhide commented on lib/gettext/plural.ex
> +  @type opts :: locale() | term()
Let's rename this to something else, since `opts` doesn't convey what this is. `plural_info`?

Also, why have `locale() | term()` instead of just `term()`?

2023-01-19 12:58 UTC, whatyouhide commented on lib/gettext/plural.ex
> +    {:module, ^plural_mod} = Code.ensure_loaded(plural_mod)
Should this give a better error message if the `plural_mod` is not loaded, explaining why it needs to be loaded?

2023-01-19 12:58 UTC, whatyouhide commented on lib/mix/tasks/gettext.merge.ex
> +    * `--plural-forms-header` - `Plural-Forms` header content as string.
This is a breaking change. We can't remove the `--plural-forms` option?

2023-01-19 12:58 UTC, whatyouhide commented on lib/mix/tasks/gettext.merge.ex
> +      Mix.raise("The :plural_forms option is deprecated in favor of :plural_forms_header")
This is not a deprecation, if we're raising here. Let's not even deprecate this for now, let's just support both. Deprecations can always be done later.

2023-01-19 14:41 UTC, maennchen commented on lib/gettext/plural.ex
> +  @callback plural_forms_header(locale()) :: String.t() | nil
It means that it does not know a rule for that locale. The caller of the function will then just set a partial header with only nplurals defined.

2023-01-19 14:46 UTC, maennchen commented on lib/gettext/plural.ex
> +  @type opts :: locale() | term()
@whatyouhide I set `opts` based on `plug` semantics: https://github.com/elixir-plug/plug/blob/15445099f5cdd9a196bd77c515e6fb82f1d4801d/lib/plug.ex#L57

In the case where the the optional callback `init/1` is implemented, it can set it to any value it wants. In the case where it is not defined, it will be set to the `locale`.

This is implemented this way so that the `Gettext.Plural` behaviour does not have a breaking change. Otherwise, I would probably not set it as optional or just set it to `nil` if it is not defined.

2023-01-19 14:49 UTC, maennchen commented on lib/gettext/plural.ex
> +    {:module, ^plural_mod} = Code.ensure_loaded(plural_mod)
@whatyouhide I needed to put it into place since it is loaded automatically if a function is called but not to check with `function_exported?`.

We can yield an error though if it cant be loaded.

Something like this?

```suggestion
    case Code.ensure_loaded(plural_mod) do
      {:module, ^plural_mod} -> :ok
      _other -> raise "The module #{plural_mode} can't be found." # Better message?
    end
```

2023-01-19 14:52 UTC, maennchen commented on lib/mix/tasks/gettext.merge.ex
> +    * `--plural-forms-header` - `Plural-Forms` header content as string.
@whatyouhide It was only supposed to be a deprecation and not a removal except that I used `Mix.raise` by accident.

The idea was that it is deprecated and just yields a warning.

The reason that I wanted to deprecate it is, that it has an inconsistent behaviour as it is right now. (See https://github.com/elixir-gettext/gettext/pull/343#discussion_r1071094099)

2023-01-19 14:53 UTC, maennchen commented on lib/mix/tasks/gettext.merge.ex
> +    * `--plural-forms-header` - `Plural-Forms` header content as string.
Based on the information in the comment above:

* Would you like me to not deprecate it and keep it inconsistent?
* Or would you like me to fix the `Mix.raise` by using an actual warning like I intended?

2023-01-19 15:02 UTC, maennchen commented on lib/gettext/plural.ex
> +  @callback plural_forms_header(locale()) :: String.t() | nil
Ignore my previous comment, that is not factually correct. That's what's supposed to happen though. I'll have a look.

2023-01-19 15:06 UTC, maennchen commented on lib/gettext/plural.ex
> +  @callback plural_forms_header(locale()) :: String.t() | nil
Now it is as I described.

2023-01-19 16:26 UTC, josevalim commented on lib/gettext/plural.ex
> +    case read_plural_forms_from_headers(plural_forms_header) do
Maybe we can deprecate the option and guide users towards the new solution.

2023-01-19 16:30 UTC, maennchen commented on lib/gettext/plural.ex
> +    {:module, ^plural_mod} = Code.ensure_loaded(plural_mod)
@josevalim I initially used that one. Unfortunately, this lib supports 1.11 and `ensure_loaded!` was introduced in 1.12.

2023-01-20 08:32 UTC, whatyouhide commented on lib/gettext/plural.ex
> +  @type opts :: locale() | term()
I definitely agree that the pattern of having `init/1` optional and returning a term that then is passed down is great. I'm just thinking that the **name** `opts` is not good. I don't think it's good in Plug either, FWIW 😄 That's why I was suggesting `plural_info`.

As per the typespec, in Plug there is not `term()`, so I think here you can reduce the typespec to just `term()`.

2023-01-20 08:32 UTC, whatyouhide commented on lib/gettext/plural.ex
> +    {:module, ^plural_mod} = Code.ensure_loaded(plural_mod)
@maennchen define `ensure_loaded!/1` in this module conditionally, something like this

```elixir
# TODO: remove when we depend on Elixir 1.12+
if function_exported?(Code, :ensure_loaded!, 1) do
  defp ensure_loaded!(mod), do: Code.ensure_loaded!(mod)
else
  defp ensure_loaded!(mod) do
    case Code.ensure_loaded(mod) do
      {:module, ^mod} -> :ok
      _other -> raise "<good error message>"
    end
  end
end
```

2023-01-20 08:32 UTC, whatyouhide commented on lib/gettext/plural.ex
> +    if plural_forms_header != nil do
Nitpick

```suggestion
    if plural_forms_header do
```

2023-01-20 08:32 UTC, whatyouhide commented on lib/mix/tasks/gettext.merge.ex
> +    * `--plural-forms-header` - `Plural-Forms` header content as string.
For now, let's not deprecate and keep it inconsistent. We can do the **soft** deprecation (warning) in a later PR, so that we can keep this PR more focused.

2023-01-20 10:45 UTC, maennchen commented on lib/gettext/plural.ex
> +    case read_plural_forms_from_headers(plural_forms_header) do
@josevalim That is what I intended to do here: https://github.com/elixir-gettext/gettext/pull/343#discussion_r1081382215

Based on the discussion with @whatyouhide I will probably ignore the whole topic for the PR.

2023-01-20 14:47 UTC, maennchen commented
@whatyouhide I've adressed all the comments except https://github.com/elixir-gettext/gettext/pull/343#discussion_r1081221654

Are we sure that we handle the deprecation question correctly? I have removed it but find it a bit strange to keep code (and not even discourage using it) when the behaviour it causes is potentially flawed.

2023-01-20 15:17 UTC, whatyouhide approved these changes
This is great for now, we can deprecate the `--plural-forms` option later. 💯

2023-01-20 15:17 UTC, merged

2023-01-20 16:05 UTC, maennchen commented
@whatyouhide / @josevalim 
Quick note: I will have some surgery on my wrist next week. I will probably not have time to finish the Gettext.Plural implementation for expo until then.
I however plan to pick it back up 2/3 weeks later when I can hopefully get rid of the cast and properly type again.

2023-01-20 20:26 UTC, whatyouhide commented
@maennchen no worries! I have some free time, so I can give it a shot if you want. I'm working on polishing docs as well. Thanks for all the work!! 💟

2023-01-20 21:40 UTC, maennchen commented
@whatyouhide If you’d like to, I don’t mind if you pick it up from here. But otherwise I’m also fine doing myself in a few weeks. However you prefer 😊 I might be able to do some code reviews, so just let me know if I can help.