Fix duplicated filename in reference when using write_reference_line_numbers
elixir-gettext/gettext pull request #345
Opened 2023-01-17 15:20 UTC by agenestar

Fixes #344

2023-01-17 15:52 UTC, maennchen commented on test/gettext/merger_test.exs
> +              [{"path/to/other_file.ex", 24}]
How does this behave with this?

```suggestion
              [{"path/to/file.ex", 12}, {"path/to/file.ex", 24}],
              [{"path/to/file.ex", 42}],
              [{"path/to/other_file.ex", 24}]
```

2023-01-17 16:22 UTC, agenestar commented on test/gettext/merger_test.exs
> +              [{"path/to/other_file.ex", 24}]
Thanks for your help! It fails with these modifications. 

I have added your suggestion and modified the function to have unique filenames also at the reference level. Im not 100% sure about the code style in the prune_references function but it is working right now.

2023-01-17 16:32 UTC, agenestar commented on test/gettext/merger_test.exs
> +              [{"path/to/other_file.ex", 24}]
Sorry, but it is my first contribution to gettext. Can you give me an example of a scenario where this could happen?

2023-01-17 16:40 UTC, maennchen commented on test/gettext/merger_test.exs
> +              [{"path/to/other_file.ex", 24}]
Sure :)

Gettext should be able to handle any valid `.po` file. This is valid:

```elixir
Mix.install([{:expo, "~> 0.2"}])

"""
#: file:1 file:2
#: file:3
#: other_file:1
msgid "how are you," " friend?"
msgstr "come stai,"
"""
|> Expo.PO.parse_string!()
|> dbg()
```

```
[example.exs:11: (file)]
"#: file:1 file:2\n#: file:3\n#: other_file:1\nmsgid \"how are you,\" \" friend?\"\nmsgstr \"come stai,\"\n" #=> "#: file:1 file:2\n#: file:3\n#: other_file:1\nmsgid \"how are you,\" \" friend?\"\nmsgstr \"come stai,\"\n"
|> Expo.PO.parse_string!() #=> %Expo.Messages{
  headers: [],
  messages: [
    #Expo.Message.Singular<
      msgid: ["how are you,", " friend?"],
      msgstr: ["come stai,"],
      msgctxt: nil,
      comments: [],
      extracted_comments: [],
      flags: [],
      previous_messages: [],
      references: [
        [{"file", 1}, {"file", 2}],
        [{"file", 3}],
        [{"other_file", 1}]
      ],
      obsolete: false,
      ...
    >
  ],
  top_comments: [],
  file: nil
}
```

As long as gettext is the creator of a message, that will normally not happen, because it automatically puts every reference on a new line:

https://github.com/elixir-gettext/gettext/blob/2ebe8066d6309ea2d810beb93e38433fef6f5071/lib/gettext/extractor.ex#L186

There's however also `.po` editors out there that decide the line splitting based on the line width. So it is fully possible that a file contains those kind of entries after it has been handled by an outside tool.

2023-01-18 13:50 UTC, maennchen requested changes

2023-01-18 13:50 UTC, maennchen commented on lib/gettext/merger.ex
> +        all.messages
```suggestion
```

2023-01-18 13:51 UTC, maennchen approved these changes

2023-01-18 14:00 UTC, agenestar commented
Thanks @maennchen for your help :)

2023-01-19 12:35 UTC, merged